#! /bin/bash

#cd /root/sandbox/upstream/glusterfs
make uninstall
make clean
make distclean
rm -rf /usr/local/var/log/glusterfs
rm -rf /usr/local/var/run/gluster*
rm -rf /usr/local/etc/glusterfs
rm -rf /usr/local/lib/glusterfs
rm -rf /usr/local/include/glusterfs
rm -rf /usr/local/share/glusterfs
rm -rf /usr/local/libexec/glusterfs
rm -rf /usr/local/lib/ocf/resource.d/glusterfs
rm -rf /usr/local/share/doc/glusterfs
rm -rf /usr/local/share/doc/glusterfs/benchmarking
rm -rf /usr/local/var/lib/glusterd
rm -rf /usr/local/var/lib/misc/glusterfsd
rm -rf /var/log/glusterfs
rm -rf /var/run/gluster*
rm -rf /var/lib/misc/glusterfsd
rm -rf /var/lib/glusterd
rm -rf /etc/glusterfs
rm -rf /usr/lib/glusterfs
rm -rf /usr/include/glusterfs
rm -rf /usr/share/glusterfs
rm -rf /usr/libexec/glusterfs
rm -rf /usr/lib/ocf/resource.d/glusterfs
rm -rf /usr/share/doc/glusterfs
rm -rf /usr/share/doc/glusterfs/benchmarking
