#! /bin/bash

#cd /root/sandbox/upstream/*
nproc=$(getconf _NPROCESSORS_ONLN)
./autogen.sh
./configure --enable-debug --enable-gnfs
make install CFLAGS="-g -O1 -Wall" -j ${nproc}
ldconfig /usr/local/lib
ldconfig -p | grep libgf
