#! /bin/bash

#cd /root/sandbox/upstream/*
nproc=$(getconf _NPROCESSORS_ONLN)
./autogen.sh
./configure --enable-gnfs --enable-asan
make install -j ${nproc}
ldconfig /usr/local/lib
ldconfig -p | grep libgf
