#! /bin/bash

cd /root/sandbox/downstream/*
nproc=$(getconf _NPROCESSORS_ONLN)
./autogen.sh
./configure --enable-debug --enable-tiering --enable-gnfs
make install CFLAGS="-g -O0 -Wall -std=gnu89" -j ${nproc}
ldconfig /usr/local/lib
ldconfig -p | grep libgf
